/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "test.check" instead.
 */

#include <check.h>

#include "s21_math.h"
#include <math.h>
#include <stdlib.h>

START_TEST(s21_abs_1)
{
int num = -4657;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_2)
{
int num = -3425;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_3)
{
int num = 1106;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_4)
{
int num = 2419;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_5)
{
int num = -9641;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_6)
{
int num = -7500;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_7)
{
int num = 1692;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_8)
{
int num = -1808;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_9)
{
int num = -1144;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_10)
{
int num = -6051;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_11)
{
int num = -4871;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_12)
{
int num = 2377;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_13)
{
int num = -1058;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_14)
{
int num = -7180;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_15)
{
int num = 8128;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_16)
{
int num = -454;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_17)
{
int num = -1714;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_18)
{
int num = -7330;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_19)
{
int num = 1397;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_20)
{
int num = 6768;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_21)
{
int num = 2824;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_22)
{
int num = 5966;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_23)
{
int num = 4625;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_24)
{
int num = -7898;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_25)
{
int num = 1563;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_26)
{
int num = 9206;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_27)
{
int num = 910;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_28)
{
int num = 382;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_29)
{
int num = -9343;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_30)
{
int num = 1148;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_31)
{
int num = -2692;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_32)
{
int num = -4615;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_33)
{
int num = 3184;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_34)
{
int num = -2876;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_35)
{
int num = 7633;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_36)
{
int num = 229;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_37)
{
int num = -5844;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_38)
{
int num = -3658;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_39)
{
int num = -7584;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_40)
{
int num = 7869;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_41)
{
int num = -1714;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_42)
{
int num = 136;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_43)
{
int num = 555;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_44)
{
int num = 8909;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_45)
{
int num = 7531;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_46)
{
int num = -6055;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_47)
{
int num = -1449;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_48)
{
int num = 9843;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_49)
{
int num = -2229;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_50)
{
int num = -2780;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_51)
{
int num = 1851;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_52)
{
int num = -1646;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_53)
{
int num = 2711;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_54)
{
int num = -7770;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_55)
{
int num = -2973;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_56)
{
int num = -5423;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_57)
{
int num = 5386;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_58)
{
int num = -6633;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_59)
{
int num = -8759;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_60)
{
int num = -4245;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_61)
{
int num = -2359;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_62)
{
int num = -7087;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_63)
{
int num = -7623;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_64)
{
int num = -3753;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_65)
{
int num = -1124;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_66)
{
int num = -7420;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_67)
{
int num = -1007;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_68)
{
int num = -2103;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_69)
{
int num = 6985;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_70)
{
int num = -7629;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_71)
{
int num = -7694;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_72)
{
int num = 1296;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_73)
{
int num = 8969;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_74)
{
int num = 1629;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_75)
{
int num = 149;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_76)
{
int num = -3693;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_77)
{
int num = -1531;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_78)
{
int num = -8535;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_79)
{
int num = 7246;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_80)
{
int num = 4781;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_81)
{
int num = -3442;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_82)
{
int num = -6358;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_83)
{
int num = 5261;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_84)
{
int num = -9583;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_85)
{
int num = -6094;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_86)
{
int num = 2542;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_87)
{
int num = -9651;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_88)
{
int num = -2130;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_89)
{
int num = -3606;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_90)
{
int num = 1526;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_91)
{
int num = 9289;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_92)
{
int num = 7926;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_93)
{
int num = -5575;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_94)
{
int num = -5085;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_95)
{
int num = -3062;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_96)
{
int num = -1470;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_97)
{
int num = 6847;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_98)
{
int num = -9979;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_99)
{
int num = -9613;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

START_TEST(s21_abs_100)
{
int num = 6283;
ck_assert_int_eq(abs(num), s21_abs(num));
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, s21_abs_1);
    tcase_add_test(tc1_1, s21_abs_2);
    tcase_add_test(tc1_1, s21_abs_3);
    tcase_add_test(tc1_1, s21_abs_4);
    tcase_add_test(tc1_1, s21_abs_5);
    tcase_add_test(tc1_1, s21_abs_6);
    tcase_add_test(tc1_1, s21_abs_7);
    tcase_add_test(tc1_1, s21_abs_8);
    tcase_add_test(tc1_1, s21_abs_9);
    tcase_add_test(tc1_1, s21_abs_10);
    tcase_add_test(tc1_1, s21_abs_11);
    tcase_add_test(tc1_1, s21_abs_12);
    tcase_add_test(tc1_1, s21_abs_13);
    tcase_add_test(tc1_1, s21_abs_14);
    tcase_add_test(tc1_1, s21_abs_15);
    tcase_add_test(tc1_1, s21_abs_16);
    tcase_add_test(tc1_1, s21_abs_17);
    tcase_add_test(tc1_1, s21_abs_18);
    tcase_add_test(tc1_1, s21_abs_19);
    tcase_add_test(tc1_1, s21_abs_20);
    tcase_add_test(tc1_1, s21_abs_21);
    tcase_add_test(tc1_1, s21_abs_22);
    tcase_add_test(tc1_1, s21_abs_23);
    tcase_add_test(tc1_1, s21_abs_24);
    tcase_add_test(tc1_1, s21_abs_25);
    tcase_add_test(tc1_1, s21_abs_26);
    tcase_add_test(tc1_1, s21_abs_27);
    tcase_add_test(tc1_1, s21_abs_28);
    tcase_add_test(tc1_1, s21_abs_29);
    tcase_add_test(tc1_1, s21_abs_30);
    tcase_add_test(tc1_1, s21_abs_31);
    tcase_add_test(tc1_1, s21_abs_32);
    tcase_add_test(tc1_1, s21_abs_33);
    tcase_add_test(tc1_1, s21_abs_34);
    tcase_add_test(tc1_1, s21_abs_35);
    tcase_add_test(tc1_1, s21_abs_36);
    tcase_add_test(tc1_1, s21_abs_37);
    tcase_add_test(tc1_1, s21_abs_38);
    tcase_add_test(tc1_1, s21_abs_39);
    tcase_add_test(tc1_1, s21_abs_40);
    tcase_add_test(tc1_1, s21_abs_41);
    tcase_add_test(tc1_1, s21_abs_42);
    tcase_add_test(tc1_1, s21_abs_43);
    tcase_add_test(tc1_1, s21_abs_44);
    tcase_add_test(tc1_1, s21_abs_45);
    tcase_add_test(tc1_1, s21_abs_46);
    tcase_add_test(tc1_1, s21_abs_47);
    tcase_add_test(tc1_1, s21_abs_48);
    tcase_add_test(tc1_1, s21_abs_49);
    tcase_add_test(tc1_1, s21_abs_50);
    tcase_add_test(tc1_1, s21_abs_51);
    tcase_add_test(tc1_1, s21_abs_52);
    tcase_add_test(tc1_1, s21_abs_53);
    tcase_add_test(tc1_1, s21_abs_54);
    tcase_add_test(tc1_1, s21_abs_55);
    tcase_add_test(tc1_1, s21_abs_56);
    tcase_add_test(tc1_1, s21_abs_57);
    tcase_add_test(tc1_1, s21_abs_58);
    tcase_add_test(tc1_1, s21_abs_59);
    tcase_add_test(tc1_1, s21_abs_60);
    tcase_add_test(tc1_1, s21_abs_61);
    tcase_add_test(tc1_1, s21_abs_62);
    tcase_add_test(tc1_1, s21_abs_63);
    tcase_add_test(tc1_1, s21_abs_64);
    tcase_add_test(tc1_1, s21_abs_65);
    tcase_add_test(tc1_1, s21_abs_66);
    tcase_add_test(tc1_1, s21_abs_67);
    tcase_add_test(tc1_1, s21_abs_68);
    tcase_add_test(tc1_1, s21_abs_69);
    tcase_add_test(tc1_1, s21_abs_70);
    tcase_add_test(tc1_1, s21_abs_71);
    tcase_add_test(tc1_1, s21_abs_72);
    tcase_add_test(tc1_1, s21_abs_73);
    tcase_add_test(tc1_1, s21_abs_74);
    tcase_add_test(tc1_1, s21_abs_75);
    tcase_add_test(tc1_1, s21_abs_76);
    tcase_add_test(tc1_1, s21_abs_77);
    tcase_add_test(tc1_1, s21_abs_78);
    tcase_add_test(tc1_1, s21_abs_79);
    tcase_add_test(tc1_1, s21_abs_80);
    tcase_add_test(tc1_1, s21_abs_81);
    tcase_add_test(tc1_1, s21_abs_82);
    tcase_add_test(tc1_1, s21_abs_83);
    tcase_add_test(tc1_1, s21_abs_84);
    tcase_add_test(tc1_1, s21_abs_85);
    tcase_add_test(tc1_1, s21_abs_86);
    tcase_add_test(tc1_1, s21_abs_87);
    tcase_add_test(tc1_1, s21_abs_88);
    tcase_add_test(tc1_1, s21_abs_89);
    tcase_add_test(tc1_1, s21_abs_90);
    tcase_add_test(tc1_1, s21_abs_91);
    tcase_add_test(tc1_1, s21_abs_92);
    tcase_add_test(tc1_1, s21_abs_93);
    tcase_add_test(tc1_1, s21_abs_94);
    tcase_add_test(tc1_1, s21_abs_95);
    tcase_add_test(tc1_1, s21_abs_96);
    tcase_add_test(tc1_1, s21_abs_97);
    tcase_add_test(tc1_1, s21_abs_98);
    tcase_add_test(tc1_1, s21_abs_99);
    tcase_add_test(tc1_1, s21_abs_100);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
